"""init

Revision ID: d318125370c5
Revises: 
Create Date: 2020-10-01 21:21:28.568514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd318125370c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROCESSED_SMS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'FAILURE', 'DOUBLE', 'NOT_FOUND', name='smsstatusenum'), nullable=False),
    sa.Column('sender', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=400), nullable=True),
    sa.Column('answer', sa.String(length=400), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PROCESSED_SMS_date'), 'PROCESSED_SMS', ['date'], unique=False)
    op.create_index(op.f('ix_PROCESSED_SMS_status'), 'PROCESSED_SMS', ['status'], unique=False)
    op.create_table('invalids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invalid_serial', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invalids_invalid_serial'), 'invalids', ['invalid_serial'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_name', sa.String(length=200), nullable=True),
    sa.Column('log_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('start_serial', sa.String(length=30), nullable=True),
    sa.Column('end_serial', sa.String(length=30), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serials_end_serial'), 'serials', ['end_serial'], unique=False)
    op.create_index(op.f('ix_serials_start_serial'), 'serials', ['start_serial'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serials_start_serial'), table_name='serials')
    op.drop_index(op.f('ix_serials_end_serial'), table_name='serials')
    op.drop_table('serials')
    op.drop_table('logs')
    op.drop_index(op.f('ix_invalids_invalid_serial'), table_name='invalids')
    op.drop_table('invalids')
    op.drop_index(op.f('ix_PROCESSED_SMS_status'), table_name='PROCESSED_SMS')
    op.drop_index(op.f('ix_PROCESSED_SMS_date'), table_name='PROCESSED_SMS')
    op.drop_table('PROCESSED_SMS')
    # ### end Alembic commands ###
